# Copyright (c) 2023 Andrea Cervesato <andrea.cervesato@suse.com>

name: Unit tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Git checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential check python3-pip ninja-build
        python3 -m pip install pytest msgpack meson

    - name: Build
      run: |
        meson setup build
        cd build
        meson compile

    - name: Test
      run: |
        cd build
        meson configure -D build_tests=true
        meson test

    - name: Test LTX
      run: python3 -m pytest -v tests/test_ltx.py
