# Copyright (c) 2023 Andrea Cervesato <andrea.cervesato@suse.com>

name: Unit tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Git checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential check python3-pip
        python3 -m pip install pytest msgpack

    - name: Build binray
      run: make

    - name: Build library
      run: make shared

    - name: Build tests
      run: |
        gcc --version
        make --version
        make test

    - name: Test utils
      run: ./tests/test_utils

    - name: Test unpack
      run: ./tests/test_unpack

    - name: Test message
      run: ./tests/test_message

    - name: Test LTX
      run: python3 -m pytest -v tests/test_ltx.py
